apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0bda0e32e3377f879,subnet-0641e572520baca6d"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: microservice-app
